//! Database schema definitions (Diesel)
//!
//! This file is normally auto-generated by Diesel CLI after running migrations.
//! To regenerate: diesel print-schema > src/db/schema.rs

// @generated automatically by Diesel CLI.

diesel::table! {
    audit_log (id) {
        id -> Uuid,
        timestamp -> Timestamptz,
        user_id -> Nullable<Varchar>,
        action -> Varchar,
        entity_type -> Varchar,
        entity_id -> Uuid,
        old_values -> Nullable<Jsonb>,
        new_values -> Nullable<Jsonb>,
        ip_address -> Nullable<Varchar>,
        user_agent -> Nullable<Text>,
    }
}

diesel::table! {
    organization_addresses (id) {
        id -> Uuid,
        organization_id -> Uuid,
        use_type -> Nullable<Varchar>,
        line1 -> Nullable<Varchar>,
        line2 -> Nullable<Varchar>,
        city -> Nullable<Varchar>,
        state -> Nullable<Varchar>,
        postal_code -> Nullable<Varchar>,
        country -> Nullable<Varchar>,
        is_primary -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    organization_contacts (id) {
        id -> Uuid,
        organization_id -> Uuid,
        system -> Varchar,
        value -> Varchar,
        use_type -> Nullable<Varchar>,
        is_primary -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    organization_identifiers (id) {
        id -> Uuid,
        organization_id -> Uuid,
        use_type -> Nullable<Varchar>,
        identifier_type -> Varchar,
        system -> Varchar,
        value -> Varchar,
        assigner -> Nullable<Varchar>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    organizations (id) {
        id -> Uuid,
        active -> Bool,
        name -> Varchar,
        alias -> Array<Text>,
        org_type -> Array<Text>,
        part_of -> Nullable<Uuid>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        created_by -> Nullable<Varchar>,
        updated_by -> Nullable<Varchar>,
        deleted_at -> Nullable<Timestamptz>,
        deleted_by -> Nullable<Varchar>,
    }
}

diesel::table! {
    patient_addresses (id) {
        id -> Uuid,
        patient_id -> Uuid,
        use_type -> Nullable<Varchar>,
        line1 -> Nullable<Varchar>,
        line2 -> Nullable<Varchar>,
        city -> Nullable<Varchar>,
        state -> Nullable<Varchar>,
        postal_code -> Nullable<Varchar>,
        country -> Nullable<Varchar>,
        is_primary -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    patient_contacts (id) {
        id -> Uuid,
        patient_id -> Uuid,
        system -> Varchar,
        value -> Varchar,
        use_type -> Nullable<Varchar>,
        is_primary -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    patient_identifiers (id) {
        id -> Uuid,
        patient_id -> Uuid,
        use_type -> Nullable<Varchar>,
        identifier_type -> Varchar,
        system -> Varchar,
        value -> Varchar,
        assigner -> Nullable<Varchar>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    patient_links (id) {
        id -> Uuid,
        patient_id -> Uuid,
        other_patient_id -> Uuid,
        link_type -> Varchar,
        created_at -> Timestamptz,
        created_by -> Nullable<Varchar>,
    }
}

diesel::table! {
    patient_match_scores (id) {
        id -> Uuid,
        patient_id -> Uuid,
        candidate_id -> Uuid,
        total_score -> Numeric,
        name_score -> Nullable<Numeric>,
        birth_date_score -> Nullable<Numeric>,
        gender_score -> Nullable<Numeric>,
        address_score -> Nullable<Numeric>,
        identifier_score -> Nullable<Numeric>,
        calculated_at -> Timestamptz,
    }
}

diesel::table! {
    patient_names (id) {
        id -> Uuid,
        patient_id -> Uuid,
        use_type -> Nullable<Varchar>,
        family -> Varchar,
        given -> Array<Text>,
        prefix -> Array<Text>,
        suffix -> Array<Text>,
        is_primary -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    patients (id) {
        id -> Uuid,
        active -> Bool,
        gender -> Varchar,
        birth_date -> Nullable<Date>,
        deceased -> Bool,
        deceased_datetime -> Nullable<Timestamptz>,
        marital_status -> Nullable<Varchar>,
        multiple_birth -> Nullable<Bool>,
        managing_organization_id -> Nullable<Uuid>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        created_by -> Nullable<Varchar>,
        updated_by -> Nullable<Varchar>,
        deleted_at -> Nullable<Timestamptz>,
        deleted_by -> Nullable<Varchar>,
    }
}

diesel::joinable!(organization_addresses -> organizations (organization_id));
diesel::joinable!(organization_contacts -> organizations (organization_id));
diesel::joinable!(organization_identifiers -> organizations (organization_id));
diesel::joinable!(patient_addresses -> patients (patient_id));
diesel::joinable!(patient_contacts -> patients (patient_id));
diesel::joinable!(patient_identifiers -> patients (patient_id));
diesel::joinable!(patient_links -> patients (patient_id));
diesel::joinable!(patient_match_scores -> patients (patient_id));
diesel::joinable!(patient_names -> patients (patient_id));
diesel::joinable!(patients -> organizations (managing_organization_id));

diesel::allow_tables_to_appear_in_same_query!(
    audit_log,
    organization_addresses,
    organization_contacts,
    organization_identifiers,
    organizations,
    patient_addresses,
    patient_contacts,
    patient_identifiers,
    patient_links,
    patient_match_scores,
    patient_names,
    patients,
);
